on: push
name: cibuild on push
permissions:
  contents: read
jobs:
  build:
    name: "GitHub Pages Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
    - uses: actions/checkout@v4
    - name: script/cibuild-docker
      run: script/cibuild-docker
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
